apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sensor-qc.fullname" . }}
  labels:
    {{- include "sensor-qc.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sensor-qc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_FILE_PATH
              value: {{ .Values.env.LOG_FILE_PATH }}
          volumeMounts:
            - name: log-file
              mountPath: /app
              subPath: logs.txt
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: log-file
          configMap:
            name: log-file
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
